# This file has similar workflow to build-test-lint-simple but breaks down jobs to allow for
# concurrent runs for Test/lint and Cypress test. Jobs run in their respective env so they don't
# interfere with each others.
# When jobs run in their respective env, we rely on caching necessary files such as node_modules
#  and cypress binary.
# @Todo: determine correctly cache necessary files and give correct keys so the lint job passes.
# @todo: Determine and fix why getConflict and cypress tests file ops fail.

name: Build, Test, Lint for Pull Requests
env:
  CI: true
  FORCE_COLOR: 1
on:
  pull_request:
    branches:
      - main
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # install a specific version of Node using
      # https://github.com/actions/setup-node
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      # just so we learn about available environment variables GitHub provides
      - name: Print CI env variables
        run: |
          npm i -g @bahmutov/print-env@2
          print-env GITHUB BUILD ACTIONS || true

      # Restore the previous NPM modules and Cypress binary archives.
      # Any updated archives will be saved automatically after the entire
      # workflow successfully finishes.
      # See https://github.com/actions/cache
      - name: Cache central NPM modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          #todo: What should the key that tells gh actions to invalidate the cache?
          key: ${{ runner.os }}-node-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
      - name: Cache Cypress binary
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
      # Cache local node_modules to pass to testing jobs
      - name: Cache local node_modules
        uses: actions/cache@v2
        # Todo: What are the correct paths? In order to get the test to run correctly we needed
        # to add lib & dist.
        with:
          path: |
            node_modules
            */*/node_modules
            lib
            */*/lib
            dist
            */*/dist
          key: ${{ runner.os }}-node-modules-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}

      - name: install dependencies and verify Cypress
        env:
          # make sure every Cypress install prints minimal information
          CI: 1
        run: |
          npm ci
          npx cypress cache path
          npx cypress cache list
          npx cypress verify
          npx cypress info

      - name: Build
        run: npm run setup

  test-lint:
    name: Test & Lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2

      # install a specific version of Node using
      # https://github.com/actions/setup-node
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # Restore just local node_modules.
      - name: Cache local node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
            lib
            */*/lib
            dist
            */*/dist
          key: ${{ runner.os }}-node-modules-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
      - name: Test
        run: npm run test --verbose
      # @Todo: lint is failing when it's running in a separate job.
      # - name: Lint
      #   run: npm run lint
  cypress:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      # @todo we may not need this if using
      # uses: cypress-io/github-action@v2
      # install a specific version of Node using
      # https://github.com/actions/setup-node
      # - name: Use Node.js v12
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 12
      # Restore just local node_modules and the Cypress binary archives.
      - name: Cache Cypress binary
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
      # Restore local node_modules and build files.
      - name: Cache local node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
            lib
            */*/lib
            dist
            */*/dist
          key: ${{ runner.os }}-node-modules-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
      # check the restored Cypress binary
      - name: Check binary
        run: |
          npx cypress cache path
          npx cypress cache list
      # Starts local server, then runs Cypress tests and records results on the dashboard
      # npx cypress run --record --parallel --group "Parallel 2x"
      #--parallel --group "Parallel 2x"
      - name: Cypress tests
        uses: cypress-io/github-action@v2
        env:
          # place your secret record key at
          # https://github.com/cypress-io/cypress-example-kitchensink/settings/secrets
          #CYPRESS_RECORD_KEY: ${{ secrets.dashboardRecordKey }}
          TERM: xterm
