name: Build, Test, Lint for Pull Requests
env:
  CI: true
  FORCE_COLOR: 1
  BODILESS_BACKEND_TMP: ./temp

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup, Build, Lint and Test
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # install a specific version of Node using
      # https://github.com/actions/setup-node
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      # just so we learn about available environment variables GitHub provides
      - name: Print CI env variables
        run: |
          npm i -g @bahmutov/print-env@2
          print-env GITHUB BUILD ACTIONS || true

      - name: Print Git Version
        run: git --version

      - name: Creat temp directory For test
        run: mkdir ./temp


      - name: Git Log
        run: git log  --pretty=oneline | head -n 10

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run setup

      - name: Test
        run: npm run test --quiet --colors

#      - name: Lint
#        run: npm run lint
#
#      - name: Cypress tests
#        run: |
#          npm run test:ci
